// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvlGaMhcl7KWNXIBID4veuQ3pRrxil_Tc',
    appId: '1:938796001232:web:8e110bf5dcc6d5d81e3bd5',
    messagingSenderId: '938796001232',
    projectId: 'medical-center-df926',
    authDomain: 'medical-center-df926.firebaseapp.com',
    storageBucket: 'medical-center-df926.appspot.com',
    measurementId: 'G-N3NX0334MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKSMHE_3VWJyESjZ9r87kfSMzjPutMnQA',
    appId: '1:938796001232:android:f920b1a4d4272a801e3bd5',
    messagingSenderId: '938796001232',
    projectId: 'medical-center-df926',
    storageBucket: 'medical-center-df926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1xKn0cBLSAuPSUfNw2aemKe3soRXqhrs',
    appId: '1:938796001232:ios:5e1055897ebcdd651e3bd5',
    messagingSenderId: '938796001232',
    projectId: 'medical-center-df926',
    storageBucket: 'medical-center-df926.appspot.com',
    iosBundleId: 'com.example.medicalCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1xKn0cBLSAuPSUfNw2aemKe3soRXqhrs',
    appId: '1:938796001232:ios:f2e28d7efa2ff2a11e3bd5',
    messagingSenderId: '938796001232',
    projectId: 'medical-center-df926',
    storageBucket: 'medical-center-df926.appspot.com',
    iosBundleId: 'com.example.medicalCenter.RunnerTests',
  );
}
